pipeline {
  agent any
  stages {
      stage('SonarQube analysis') {
          steps {
              withMaven(maven:'Maven3.6.3') {
                  sh 'mvn clean package sonar:sonar -Dsonar.projectKey=Users-Spring-Boot -Dsonar.host.url=http://localhost:9000 -Dsonar.login=848b05cbc78baac42f4b48bb379f4eabcd8f77ee'
              }
          }
      }
      stage("Quality Gate") {
          steps {
              waitForQualityGate abortPipeline: true
          }
      }
  }
}